### ISSUE TITLE
pip install memprocfs on linux fails (memprocfs==5.14.3)

### ISSUE THREAD

**Issue by BrandonFanti** [ufrisk/MemProcFS#369]
For linux users, @ufrisk fixed a bug in the build process for Linux in `memprocfs==5.14.5` that was present in 5.14.3.

I'm cherry picking the "bad" stuff - Errors mostly, in `$pip install memprocfs`:
```
  Building wheel for memprocfs (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for memprocfs (pyproject.toml) did not run successfully.
  │ exit code: 1

```
*snip*
```
gcc -c -o leechrpcclient.o leechrpcclient.c -I. -I../includes/ -D LINUX -D _GNU_SOURCE -shared -fPIC -fvisibility=hidden -pthread `pkg-config libusb-1.0 --libs --cflags` -fPIE -fPIC -pie -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O1 -Wl,-z,noexecstack -Wall -Wno-multichar -Wno-unused-result -Wno-unused-variable -Wno-unused-value -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast
      In file included from leechrpcclient.c:9:
      leechrpc.h:9:10: fatal error: leechgrpc.h: No such file or directory
          9 | #include <leechgrpc.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      make[1]: *** [Makefile:16: leechrpcclient.o] Error 1
      make[1]: Leaving directory '/tmp/pip-install-c497venh/memprocfs_8f5b8201cd3e4a3c889622704e4fbfc4/leechcore'
      make: *** [Makefile:3: all] Error 2
```
*snip*
```
gcc -shared $previous_build_output_files -L. -l:vmm.so -o build/lib.linux-x86_64-cpython-38/memprocfs/vmmpyc.abi3.so -Wl,-rpath,$ORIGIN -g -ldl -shared
      /usr/bin/ld: cannot find -l:vmm.so: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for memprocfs
Failed to build memprocfs
ERROR: Failed to build installable wheels for some pyproject.toml based projects (memprocfs)
```

Pertinent to my particular case, but not this issue (it came up indirectly, and isn't very clearly documented ATM, so I'm just mentioning it here) is that gRPC is not supported out of the box because of size constraints - it must be compiled separately.

**Comment by ufrisk** [comment]
I'll update the guide with the gRPC info, I should also try to improve on the error message you get when you're unable to initialize MemProcFS so that you'll get something better than a random TypeError.

Also, I wish to thank you for the Sponsorship. Huge thanks! 💖 

Please let me know if it's you on Discord asking questions around this, sometimes it's just very hard to know.

**Comment by BrandonFanti** [comment]
Yup, that was me. Happy to help someone as enthusiastic about their projects as I am my own- and recognize and appreciate the huge amount of work going into all of this! Thanks again for the speedy patch!
